# .github/workflows/deploy.yml
jobs:
  build:
    steps:
      - name: Build
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace placeholder in your HTML/JS with actual token
          sed -i "s/HF_TOKEN_PLACEHOLDER/$HF_TOKEN/g" index.html
